### ISSUE TITLE
How to set timeout through an external splash page with a program.

### ISSUE THREAD

**Issue by Testing42** [stuartst/cisco-wlc-captive-portal#1]
https://www.cisco.com/c/en/us/td/docs/wireless/controller/7-4/configuration/guides/consolidated/b_cg74_CONSOLIDATED/b_cg74_CONSOLIDATED_chapter_01001101.html

I want to setup the user timeout not though cli or gui, I want to use an external splash page and change the time out programmatically. Any help would be appreciated.

In your code I'm not seeing anything about timeout and I'd like some help if possible, thank you.

**Comment by stuartst** [comment]
Unfortunately, this isn't possible as there is no timeout value that can be POST'd back to the controller on a per-session basis.

The only way this can be achieved is by using a RADIUS server and responding with a unique session-timeout value for each session based on your criteria (e.g. username, user group, etc.).
